BEGIN;

-- DROP EXISTING TABLE
DROP TABLE IF EXISTS "users";

-- CREATE FRESH TABLE
CREATE TABLE IF NOT EXISTS "users" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "password" TEXT NOT NULL,
  CONSTRAINT "user" UNIQUE("name")
);

COMMIT;
