BEGIN;

-- DROP EXISTING TABLE
DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "nodes";
DROP TABLE IF EXISTS "nodeLinks";

-- CREATE FRESH TABLE
CREATE TABLE IF NOT EXISTS "users" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "password" TEXT NOT NULL,
  CONSTRAINT "user" UNIQUE("name")
);

-- CREATE FRESH TABLE
CREATE TABLE IF NOT EXISTS "nodes" (
  "id" SERIAL PRIMARY KEY  
);

-- CREATE FRESH TABLE
CREATE TABLE IF NOT EXISTS "nodeLinks" (
  "id" SERIAL PRIMARY KEY,
  "nodeFromId" INTEGER NOT NULL REFERENCES "nodes" ("id"),
  "nodeToId" INTEGER NOT NULL REFERENCES "nodes" ("id")
);

COMMIT;
